# Generated by Django 6.1.2 on 2026-10-08 05:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('auto_ack', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='JunctionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('junction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='traffic.junction')),
            ],
        ),
        migrations.CreateModel(
            name='ControllerCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.CharField(max_length=64)),
                ('direction', models.CharField(max_length=10)),
                ('requested_state', models.CharField(max_length=10)),
                ('status', models.CharField(default='PENDING', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('junction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='traffic.junction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('junction', 'command_id'), name='uniq_cmd_per_junction')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('junction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='traffic.junction')),
            ],
            options={
                'indexes': [models.Index(fields=['junction', '-id'], name='traffic_aud_junctio_7c84f3_idx')],
            },
        ),
    ]
